name: mini_make_daily

on:
  schedule:
    - cron: "7 0 * * *"  # UTC 00:07 = KST 09:07
  workflow_dispatch: {}  # 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
                - name: Debug - show which file is running
        run: |
          echo "=== LIST ==="
          ls -la
          echo "=== HEAD mini_make.py ==="
          sed -n '1,40p' mini_make.py
          echo "=== GREP markers ==="
          grep -n "HTTP_GET" -n mini_make.py || true
          grep -n "m.entertain.naver.com/ranking" -n mini_make.py || true

      - name: Run
        run: python mini_make.py
        
      - name: Debug - show naver_debug.html
        if: always()
        run: |
          echo "=== outputs dir ==="
          ls -la outputs || true
          echo "=== naver_debug.html head ==="
          sed -n '1,120p' outputs/naver_debug.html || true
